# Configuración de proyectos para Supabase CLI
project_id = ""

[api]
port = 54321
schemes = ["http", "https"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 5432

[studio]
port = 54323

[functions]
[functions.gemini-query]
verify_jwt = false 